    default: &default
      adapter: postgresql
      encoding: unicode
      pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
      username: nextcay_dev
      password: nextcay
      host: localhost
      port: 5432

    development:
      <<: *default
      database: bicycle_shop

    test:
      <<: *default
      database: bicecle_shop_test
